services:
  # Message Broker (RabbitMQ)
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    networks:
      - teste-docker

  # User API
  userapi:
    build:
      context: .
      dockerfile: UserApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server,1433;Database=VStoreUsers;User Id=sa;Password=F@b250511;TrustServerCertificate=true;MultipleActiveResultSets=true;
      - RabbitMQ__Host=rabbitmq
    ports:
      - "5000:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - teste-docker

  # Product API
  productapi:
    build:
      context: .
      dockerfile: VStore.ProductApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server,1433;Database=VStoreProduct;User Id=sa;Password=F@b250511;TrustServerCertificate=true;MultipleActiveResultSets=true;
      - RabbitMQ__Host=rabbitmq
    ports:
      - "5001:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - teste-docker

  # Order API
  orderapi:
    build:
      context: .
      dockerfile: VStore.OrderApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server,1433;Database=VStoreOrder;User Id=sa;Password=F@b250511;TrustServerCertificate=true;MultipleActiveResultSets=true;
      - RabbitMQ__Host=rabbitmq
    ports:
      - "5002:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - teste-docker

  # Email API
  emailapi:
    build:
      context: .
      dockerfile: VStore.EmailApi/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - RabbitMQ__Host=rabbitmq
    ports:
      - "5004:8080"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - teste-docker

networks:
  teste-docker:
    external: true  # 🔥 IMPORTANTE: usa a network existente